config/routes.rb
Easytowticket::Application.routes.draw do
  devise_for :admins, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'admins/registrations',
    :sessions => "admins/sessions",
    :passwords => 'admins/passwords',
    :confirmations => 'admins/confirmations'
  }

  authenticate :admin do
    namespace :admins do
      resources :admins
      resources :profile, :only => [:edit, :update]
      resources :tickets
      resources :profile, :only => [:edit, :update]
      get '/dashboard' => 'dashboards#index', as: :dashboard
      get '/' => 'dashboards#index'
    end
  end

  resources :comments
  resources :leads, :only => [:new, :create]
  post '/sign_up' => 'pages#sign_up', :as => :sign_up
  match '/contact_us' => 'leads#new', :as => :contact_us, via: :all
  match '/thanks' => 'leads#thanks', :as => :thanks, via: :all
  match "/prices" => "pages#prices", :as => :prices, via: :all
  match "/about_us" => "pages#about_us", :as => :about_us, via: :all
  match "/test" => "pages#test", :as => :test, via: :all
  root 'pages#index'
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  #has_many :comments, :as => :commenter

  before_validation { |lead| lead.zip = zip.to_s.gsub(/[^0-9]/, "").to_s }
  before_validation { |lead| lead.phone = phone.to_s.gsub(/[^0-9]/, "").to_s }

  def name
    full_name
  end

  def full_name
    first_name + ' ' + last_name
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  after_filter :subscribe, :only => [:create, :update]
  expose(:lead){
    @lead ||= params[:id] ? Lead.find(params[:id]) : Lead.new(params[:lead])
  }

  def create
    lead.status = 'new'
    lead.remoteip = request.remote_ip
    if lead.save
      flash[:notice] = t(:contacts_thanks)
      redirect_to thanks_path
    else
      render "new"
    end
  end

  private
  def subscribe
    #if params[:lead][:newsletter]
    #  lead.subscribe
    #end
  end
end

app/views/leads/new.html.haml
- content_for :pagetitle do 
  Contact Us
/ Content
.content
  / Page Header
  .page-header
    .container
      .sixteen.columns
        %h1.page-title
          Contact Us
          %span How can we help you
        %ul.breadcrumb
          %li
            =link_to t(:home), root_path
            %span.divider »
          %li.active Contact Us
  / Start Content
  .container.main
    .sixteen.columns
      .row
        =# simple_form_for(lead, :url => '', :method => 'post',  :html => {:class => 'form-horizontal' }) do |f|
        = simple_form_for(lead, :url => leads_path, :method => 'post',  :html => {:class => 'form-horizontal' }) do |f|
          - if lead.errors.count > 0
            #contact-message.alert.alert-info
              %ul.list-style
                - lead.errors.full_messages.each do |e|
                  %li.arrow-list=e
          .form-row
            %label.mws-form-label= t(:first_name)
            .form-item
            = f.input :first_name, :label => false
          .form-row
            %label.mws-form-label= t(:last_name)
            .form-item
            = f.input :last_name, :label => false
          .form-row
            %label.mws-form-label= t(:email)
            .form-item
            = f.input :email, :label => false
          .form-row
            %label.mws-form-label= t(:message)
            .form-item
            = f.input :message, :label => false
          .form-row
            %label.mws-form-label= t(:phone)
            .form-item
            = f.input :phone, :label => false
          .form-row
            %label.mws-form-label= t(:address)
            .form-item
            = f.input :address, :label => false
          .form-row
            %label.mws-form-label= t(:address2)
            .form-item
            = f.input :address2, :label => false
          .form-row
            %label.mws-form-label= t(:city)
            .form-item
            = f.input :city, :label => false
          .form-row
            %label.mws-form-label= t(:state)
            .form-item
            = f.input :state, :as => :select, :collection => us_states, :label => false
          .form-row
            %label.mws-form-label= t(:zip)
            .form-item
            = f.input :zip, :label => false
          .form-row
            %label.mws-form-label= t(:newsletter)
            .form-item
            = f.input :newsletter, as: :radio_buttons, :label => false
          .button-row
            = f.button :submit, :class => 'pull-right btn', :value => "Submit"

app/views/leads/thanks.html.haml
- content_for :pagetitle do 
  Thank You
/ Content
.content
  / Page Header
  .page-header
    .container
      .sixteen.columns
        %h1.page-title
          Thank You
          %span Your information has been received.
        %ul.breadcrumb
          %li
            =link_to t(:home), root_path
            %span.divider »
          %li
            =link_to t(:contact_us), contact_us_path
            %span.divider »
          %li.active Thank You
  / Start Content
  .container.main
    / Icons
    .columns.sixteen
      %h4.headline= t(:thank_you)
    .columns.sixteen
      %h3 Your information has been received.
      %br
    .seven.columns
      .team-contact-info
        %strong Plans & Pricing Information
        %br
        For information on our service offerings and pricing, please use the link to the right to checkout our plans and pricing. 
        %br
        %br
        =link_to t(:plans_and_pricing), prices_path(:plan => 'free'), :class => 'btn'
    .seven.columns
      %strong Sign up in 60 Seconds!
      %br
      Use our secure, online tool to sign up and get started with our service! you'll get your toll free number .
      %br
      %br
      =link_to t(:sign_up_in_60_seconds!), new_user_registration_path(:plan => 'free'), :class => 'btn'