config/routes.rb
Easytowticket::Application.routes.draw do
  devise_for :admins, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'admins/registrations',
    :sessions => "admins/sessions",
    :passwords => 'admins/passwords',
    :confirmations => 'admins/confirmations'
  }

  authenticate :admin do
    namespace :admins do
      resources :admins
      resources :profile, :only => [:edit, :update]
      resources :tickets
      resources :profile, :only => [:edit, :update]
      get '/dashboard' => 'dashboards#index', as: :dashboard
      get '/' => 'dashboards#index'
    end
  end

  resources :comments
  resources :leads, :only => [:new, :create]
  post '/sign_up' => 'pages#sign_up', :as => :sign_up
  match '/contact_us' => 'leads#new', :as => :contact_us, via: :all
  match '/thanks' => 'leads#thanks', :as => :thanks, via: :all
  match "/prices" => "pages#prices", :as => :prices, via: :all
  match "/about_us" => "pages#about_us", :as => :about_us, via: :all
  match "/test" => "pages#test", :as => :test, via: :all
  root 'pages#index'
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :account
  belongs_to :created_by, :class_name => "Admin"
  belongs_to :requested_by, :class_name => "Admin"
  belongs_to :driver, :class_name => "Admin"

  before_create :set_identification
  before_validation { |t| t.phone = phone.to_s.gsub(/[^0-9]/, "").to_s.squeeze(" ").strip }

  def milleage
    if milleage_finish && milleage_start
      milleage_finish - milleage_start
    elsif milleage_finish
      milleage_finish
    elsif milleage_start
      milleage_start
    end
  end

  def service
    if service_time_finish && service_time_start
      ((service_time_finish - service_time_start) / 1.hours).ceil
    elsif service_time_finish
      service_time_finish
    elsif service_time_start
      service_time_start
    end
  end

  def extra
    if extra_truck_finish && extra_truck_start
      ((extra_truck_finish - extra_truck_start) / 1.hours).ceil
    elsif extra_truck_finish
      extra_truck_finish
    elsif extra_truck_start
      extra_truck_start
    end
  end

  def total_charge
    10000000000000
  end
  private
  def set_identification
    self.identification = self.account.ticket_prefix + (self.account.tickets.count + 100000000).to_s
  end
end

app/controllers/admins/tickets_controller.rb
class Admins::TicketsController < AdminController
  expose(:tickets){
    if current_admin.is_admin
      current_account.tickets.order("id DESC").scoped{}
    else
      current_admin.driver_tickets.order("id DESC").scoped{}
    end
  }
  expose(:ticket, attributes: :ticket_params)

  def create
    ticket.created_by = current_admin
    if ticket.save
      redirect_to(admins_tickets_path)
    else
      render :new
    end
  end

  def update
    if ticket.update_attributes(ticket_params)
      redirect_to(admins_tickets_path)
    else
      render :edit
    end
  end

  private
  def ticket_params
    params.require(:ticket).permit!
  end
end

app/views/admins/tickets/_form.haml
= simple_form_for([:admins, ticket], :html => {:class => 'mws-form' }) do |f|
  .control-group
    %label.control-label= t(:created_by)
    .controls= f.input :created_by_id, :as => :select, :collection => current_account.admins.where(:is_driver => true, :active => true), :label => false, include_blank: false
    %label.control-label= t(:requested_by)
    .controls
      -# THIS NEEDS TO BE A PICK LIST 
      = f.input :requested_by_id, :as => :select, :collection => current_account.admins.where(:is_driver => true, :active => true), :label => false, include_blank: false
    %label.control-label= t(:driver)
    .controls= f.input :driver_id, :as => :select, :collection => current_account.admins.where(:is_driver => true), :label => false, include_blank: false
    %label.control-label= t(:truck)
    .controls
      -# This need to be current_account.trucks
      = f.input :truck_id, :as => :select, :collection => current_account.admins.where(:is_driver => true), :label => false, include_blank: false
    %label.control-label= t(:location_of_viecle)
    .controls= f.input :location_of_viecle, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:name)
    .controls= f.input :name, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:phone)
    .controls= f.input :phone, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:address)
    .controls= f.input :address, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:address2)
    .controls= f.input :address2, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:city)
    .controls= f.input :city, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:state)
    .controls= f.input :state, :as => :select, :label => false, :collection => us_states
    %label.control-label= t(:zip)
    .controls= f.input :zip, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:license_number)
    .controls= f.input :license_number, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:service_time_start)
    .controls= f.input :service_time_start, :as => :datetime_picker, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:service_time_finish)
    .controls= f.input :service_time_finish, :as => :datetime_picker, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:extra_truck_start)
    .controls= f.input :extra_truck_start, :as => :datetime_picker, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:extra_truck_finish)
    .controls= f.input :extra_truck_finish, :as => :datetime_picker, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:milleage_start)
    .controls= f.input :milleage_start, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:milleage_finish)
    .controls= f.input :milleage_finish, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:car_year)
    .controls= f.input :car_year, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:car_make)
    .controls= f.input :car_make, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:car_model)
    .controls= f.input :car_model, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:car_color)
    .controls= f.input :car_color, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:vin_number)
    .controls= f.input :vin_number, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:tag_number)
    .controls= f.input :tag_number, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:type_of_service)
    .controls
      = f.input :sling
      = f.input :hoist_tow
      = f.input :wheel_lift
      = f.input :start
      = f.input :lock_out
      = f.input :flat_tire
      = f.input :out_of_gas
      = f.input :wreck
      = f.input :recovery
    %label.control-label= t(:other)
    .controls= f.input :other, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:special_equipment)
    .controls
      = f.input :special_equipment_single_line_winching
      = f.input :special_equipment_dual_line_winching
      = f.input :special_equipment_snatch_blocks
      = f.input :special_equipment_single_line_winching
      = f.input :special_equipment_scotch_blocks
      = f.input :special_equipment_dolly
    %label.control-label= t(:other)
    .controls= f.input :special_equipment_other, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:tow_destination)
    .controls= f.input :tow_destination, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:operators_comments)
    .controls= f.input :operators_comments, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:status)
    .controls= f.input :status, :as => :select, :label => false, :collection => ticket_status
    %label.control-label= f.input :on_hold
    .control-group
    %label.control-label= t(:charges)
    %label.control-label= t(:milleage_charge)
    .controls= f.input :milleage_charge, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:towing_charge)
    .controls= f.input :towing_charge, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:labor_charge)
    .controls= f.input :labor_charge, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:storage_charge)
    .controls= f.input :storage_charge, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:storage_charge)
    .controls= f.input :administration_fee, :label => false, input_html: { class: 'required small', size: '' }
    %label.control-label= t(:tax)
    .controls= f.input :tax, :label => false, input_html: { class: 'required small', size: '' }
  .form-actions
    = f.button :submit, :class => 'btn btn-info'
    %input.btn{type: "reset", value: "Reset"}/

app/views/admins/tickets/edit.haml
.span12.widget
  .widget-header
    %span.title 
      Update Ticket #{ticket.identification}
  .widget-content.form-container
    = render 'form'

app/views/admins/tickets/index.haml
.span12.widget
  .widget-header
    %span.title 
      = link_to 'Add', new_admins_ticket_path, class: 'btn'
      Tickets #{tickets.count}
  .widget-content.table-container
    %table.table.table-striped.dataTable
      %thead
        %tr
          %th
          %th{class: 'sorting'}= t(:id)
          %th= t(:created_by)
          %th= t(:driver)
          %th= t(:created_at)
          %th= t(:location_of_viecle)
          %th= t(:name)
          %th= t(:phone)
          %th= t(:address)
          %th= t(:milleage)
          %th= t(:servie)
          %th= t(:extra)
          %th= t(:car_year)
          %th= t(:car_make)
          %th= t(:car_model)
          %th= t(:car_color)
          %th= t(:state)
          %th= t(:license_number)
          %th= t(:vin_number)
          %th= t(:type_of_service)
          %th= t(:special_equipment)
          %th= t(:updated_at)
      %tbody
        - tickets.each do |t|
          %tr
            %td= link_to 'Show', admins_ticket_path(t), class: 'btn'
            %td= t.identification
            %td= t.created_by.name if t.created_by_id
            %td= t.driver.name if t.driver_id
            %td= t.created_at.in_time_zone(current_account.time_zone).strftime('%D %r')
            %td= t.location_of_viecle
            %td= t.name
            %td= number_to_phone(t.phone)
            %td= t.address
            %td= t.milleage
            %td= t.service
            %td= t.extra
            %td= t.car_year
            %td= t.car_make
            %td= t.car_model
            %td= t.car_color
            %td= t.state
            %td= t.license_number
            %td= t.vin_number
            %td
              - if t.sling
                .badge.badge-info= t(:sling)
              - if t.hoist_tow
                .badge.badge-info= t(:hoist_tow)
              - if t.wheel_lift
                .badge.badge-info= t(:wheel_lift)
              - if t.flad_bed
                .badge.badge-info= t(:flad_bed)
              - if t.start
                .badge.badge-info= t(:start)
              - if t.lock_out
                .badge.badge-info= t(:lock_out)
              - if t.flat_tire
                .badge.badge-info= t(:flat_tire)
              - if t.out_of_gas
                .badge.badge-info= t(:out_of_gas)
              - if t.wreck
                .badge.badge-info= t(:wreck)
              - if t.recovery
                .badge.badge-info= t(:recovery)
              - unless t.other.empty?
                .badge.badge-info= 'Other ' + t.other
            %td
              - if t.special_equipment_single_line_winching?
                .badge.badge-info= 'single line winching'
              - if t.special_equipment_dual_line_winching
                .badge.badge-info= 'fual line winching'
              - if t.special_equipment_snatch_blocks
                .badge.badge-info= 'snatch blocks'
              - if t.special_equipment_scotch_blocks
                .badge.badge-info= 'scotch blocks'
              - if t.special_equipment_dolly
                .badge.badge-info= 'dolly'
              - unless t.special_equipment_other.empty?
                .badge.badge-info= 'other ' + t.special_equipment_other
            %td= t.updated_at.in_time_zone(current_account.time_zone).strftime('%D %r')

app/views/admins/tickets/new.haml
.span12.widget
  .widget-header
    %span.title 
      Add Ticket
  .widget-content.form-container
    = render 'form'

app/views/admins/tickets/show.haml
.span8.widget
  .widget-header
    %span.title Ticket Summary
    .toolbar
      .btn-group
        = link_to edit_admins_ticket_path(ticket), class: 'btn' do
          %i.icol-pencil
  .widget-content.table-container
    %table.table.table-striped.table-detail-view
      %thead
        %tr
          %th{colspan: "2"}
            %i.icol-exclamation
            = ticket.identification
      %tbody
        %tr
          %th= t(:created_by)
          %td= ticket.created_by.name
        %tr
          %th= t(:created_by)
          %td= ticket.created_by.name
        %tr
          %th= t(:created_at)
          %td= ticket.created_at.in_time_zone(current_account.time_zone).strftime('%D %r')
        %tr
          %th= t(:driver)
          %td= ticket.driver.name if ticket.driver
        -#%tr
          %th= t(:truck)
          %td= ticket.truck.name if ticket.truck
        %tr
          %th= t(:location_of_viecle)
          %td= ticket.location_of_viecle
        %tr
          %th= t(:id)
          %td= ticket.id
        %tr
          %th= t(:name)
          %td= ticket.name
        %tr
          %th= t(:phone)
          %td= ticket.phone
        %tr
          %th= t(:address)
          %td
            = ticket.address
            = ticket.address2
            = ticket.city
            = ticket.state
            = ticket.zip
        %tr
          %th= t(:license_number)
          %td= ticket.license_number
        %tr
          %th= t(:service)
          %td
            %strong Start 
            #{ticket.service_time_start.in_time_zone(current_account.time_zone).strftime('%D %r')}
            %br
            %strong Finish 
            #{ticket.service_time_finish.in_time_zone(current_account.time_zone).strftime('%D %r')}
            %br
            %strong Hours 
            #{ticket.service}
        %tr
          %th= t(:extra_truck)
          %td
            %strong Start 
            #{ticket.extra_truck_start.in_time_zone(current_account.time_zone).strftime('%D %r')}
            %br
            %strong Finish 
            #{ticket.extra_truck_finish.in_time_zone(current_account.time_zone).strftime('%D %r')}
            %br
            %strong Hours 
            #{ticket.extra}
        %tr
          %th= t(:milleage)
          %td
            %strong Start 
            #{ticket.milleage_start}
            %br
            %strong Finish 
            #{ticket.milleage_finish}
            %br
            %strong= t(:miles) 
            #{ticket.milleage}
        %tr
          %th= t(:car)
          %td
            %strong Year
            = ticket.car_year
            %br
            %strong Make
            = ticket.car_make
            %br
            %strong Model
            = ticket.car_model
            %br
            %strong Color
            = ticket.car_color
            %br
        %tr
          %th= t(:vin_number)
          %td= ticket.vin_number
        %tr
          %th= t(:tag_number)
          %td= ticket.tag_number
        %tr
          %th= t(:type_of_service)
          %td
            - if ticket.sling
              .badge.badge-info= t(:sling)
            - if ticket.hoist_tow
              .badge.badge-info= t(:hoist_tow)
            - if ticket.wheel_lift
              .badge.badge-info= t(:wheel_lift)
            - if ticket.flad_bed
              .badge.badge-info= t(:flad_bed)
            - if ticket.start
              .badge.badge-info= t(:start)
            - if ticket.lock_out
              .badge.badge-info= t(:lock_out)
            - if ticket.flat_tire
              .badge.badge-info= t(:flat_tire)
            - if ticket.out_of_gas
              .badge.badge-info= t(:out_of_gas)
            - if ticket.wreck
              .badge.badge-info= t(:wreck)
            - if ticket.recovery
              .badge.badge-info= t(:recovery)
            - unless ticket.other.empty?
              .badge.badge-info= t(:other) + ' ' + ticket.other
        %tr
          %th= t(:special_equipment)
          %td
            - if ticket.special_equipment_single_line_winching
              .badge.badge-info= t(:single_line_winching)
            - if ticket.special_equipment_dual_line_winching
              .badge.badge-info= t(:dual_line_winching)
            - if ticket.special_equipment_snatch_blocks
              .badge.badge-info= t(:snatch_blocks)
            - if ticket.special_equipment_single_line_winching
              .badge.badge-info= t(:single_line_winching)
            - if ticket.special_equipment_scotch_blocks
              .badge.badge-info= t(:scotch_blocks)
            - if ticket.special_equipment_dolly
              .badge.badge-info= t(:dolly)
            - unless ticket.other.empty?
              .badge.badge-info= t(:other) + ' ' + ticket.special_equipment_other
        %tr
          %th= t(:tow_destination)
          %td= ticket.tow_destination
        %tr
          %th= t(:operators_comments)
          %td= ticket.operators_comments
        %tr
          %th= t(:status)
          %td= ticket.status
        %tr
          %th= t(:updated_at)
          %td= ticket.updated_at.in_time_zone(current_account.time_zone).strftime('%D %r')
        %tr
          %th= t(:on_hold)
          %td
            - if ticket.on_hold
              .badge.badge-info= t(:on_hold)
.span4.widget
  .widget-header
    %span.title Charges
    .toolbar
      .btn-group
        = link_to edit_admins_ticket_path(ticket), class: 'btn' do
          %i.icol-pencil
  .widget-content.table-container
    %table.table.table-striped.table-detail-view
      %thead
        %tr
          %th{colspan: "2"}
            %i.icol-exclamation
            = ticket.identification
      %tbody
        %tr
          %th= t(:mileage)
          %td= ticket.milleage_charge
        %tr
          %th= t(:towing)
          %td= ticket.towing_charge
        %tr
          %th= t(:labor)
          %td= ticket.labor_charge
        %tr
          %th= t(:storage)
          %td= ticket.storage_charge
        %tr
          %th= t(:administration)
          %td= ticket.administration_fee
        %tr
          %th= t(:tax)
          %td= ticket.tax
        %tr
          %th= t(:total)
          %td= ticket.total_charge