config/routes.rb
Easytowticket::Application.routes.draw do
  devise_for :admins, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'admins/registrations',
    :sessions => "admins/sessions",
    :passwords => 'admins/passwords',
    :confirmations => 'admins/confirmations'
  }

  authenticate :admin do
    namespace :admins do
      resources :admins
      resources :profile, :only => [:edit, :update]
      resources :tickets
      resources :profile, :only => [:edit, :update]
      get '/dashboard' => 'dashboards#index', as: :dashboard
      get '/' => 'dashboards#index'
    end
  end

  resources :comments
  resources :leads, :only => [:new, :create]
  post '/sign_up' => 'pages#sign_up', :as => :sign_up
  match '/contact_us' => 'leads#new', :as => :contact_us, via: :all
  match '/thanks' => 'leads#thanks', :as => :thanks, via: :all
  match "/prices" => "pages#prices", :as => :prices, via: :all
  match "/about_us" => "pages#about_us", :as => :about_us, via: :all
  match "/test" => "pages#test", :as => :test, via: :all
  root 'pages#index'
end

app/views/admins/admins/_form.haml
= simple_form_for([:admins, admin], :html => {:class => 'mws-form' }) do |f|
  .mws-form-inline
    .mws-form-row.bordered
      %label.mws-form-label= t(:email)
      .mws-form-item
        = f.input :email, :label => false, input_html: { class: 'required small', size: '' }
  .mws-form-inline
    .mws-form-row.bordered
      %label.mws-form-label= t(:password)
      .mws-form-item
        = f.input :password, :label => false, input_html: { class: 'required small', size: '' }
  .mws-form-inline
    .mws-form-row.bordered
      %label.mws-form-label= t(:first_name)
      .mws-form-item
        = f.input :first_name, :label => false, input_html: { class: 'required small', size: '' }
  .mws-form-inline
    .mws-form-row.bordered
      %label.mws-form-label= t(:last_name)
      .mws-form-item
        = f.input :last_name, :label => false, input_html: { class: 'required small', size: '' }
  .mws-form-inline
    .mws-form-row.bordered
      %label.mws-form-label= t(:address)
      .mws-form-item
        = f.input :address, :label => false, input_html: { class: 'required small', size: '' }
  .mws-form-inline
    .mws-form-row.bordered
      %label.mws-form-label= t(:address2)
      .mws-form-item
        = f.input :address2, :label => false, input_html: { class: 'required small', size: '' }
  .mws-form-inline
    .mws-form-row.bordered
      %label.mws-form-label= t(:city)
      .mws-form-item
        = f.input :city, :label => false, input_html: { class: 'required small', size: '' }
  .mws-form-inline
    .mws-form-row.bordered
      %label.mws-form-label= t(:state)
      .mws-form-item
        = f.input :state, :label => false, input_html: { class: 'required small', size: '' }
  .mws-form-inline
    .mws-form-row.bordered
      %label.mws-form-label= t(:zip_code)
      .mws-form-item
        = f.input :zip_code, :label => false, input_html: { class: 'required small', size: '' }
  .mws-form-inline
    .mws-form-row.bordered
      %label.mws-form-label= t(:phone)
      .mws-form-item
        = f.input :phone, :label => false, input_html: { class: 'required small', size: '' }
  .mws-form-inline
    .mws-form-row.bordered
      %label.mws-form-label= t(:permissions)
      .mws-form-item
        = f.input :active
        = f.input :is_admin
        = f.input :is_driver
  .mws-form-inline
    .mws-form-row.bordered
      %label.mws-form-label= t(:start_date)
      .mws-form-item
        = f.input :start_date,as: :date_picker, :label => false, input_html: { class: 'required small', size: '' }
  .mws-form-inline
    .mws-form-row.bordered
      %label.mws-form-label= t(:end_date)
      .mws-form-item
        = f.input :end_date,as: :date_picker, :label => false, input_html: { class: 'required small', size: '' }
  .mws-button-row
    = f.button :submit, :class => 'btn btn-info'
    %input.btn{type: "reset", value: "Reset"}/

app/views/admins/admins/edit.haml
.mws-panel.grid_8
  .mws-panel-header
    %span Update Admin and/or Driver
  .mws-panel-body.no-padding
    = render 'form'

app/views/admins/admins/index.haml
.span12.widget
  .widget-header
    %span.title 
      = link_to 'Add', new_admins_admin_path, class: 'btn'
      Admins / Drivers
  .widget-content.table-container
    %table#demo-dtable-01.table.table-striped
      %thead
        %tr
          %th
          %th= t(:email)
          %th= t(:name)
          %th= t(:address)
          %th= t(:phone)
          %th= t(:active)
          %th= t(:is_admin)
          %th= t(:is_driver)
          %th= t(:start_date)
          %th= t(:end_date)
      %tbody
        - admins.each do |a|
          %tr
            %td= link_to 'Show', admins_admin_path(a), class: 'btn'
            %td= mail_to a.email
            %td= a.name
            %td= a.full_address
            %td= number_to_phone(a.phone)
            %td= a.active
            %td= a.is_admin
            %td= a.is_driver
            %td= a.start_date
            %td= a.end_date

app/views/admins/admins/new.haml
.mws-panel.grid_8
  .mws-panel-header
    %span Add Admin and/or Driver
  .mws-panel-body.no-padding
    = render 'form'

app/views/admins/admins/show.haml
.mws-panel.grid_8
  .mws-panel-header
    .pull-right
      = link_to 'Edit', edit_admins_admin_path(admin), class: 'btn'
    %span
      %i.icon-book
      Admin / Driver Summary
  .mws-panel-body.no-padding
    %ul.mws-summary.clearfix
      %li
        %span.key
          = t(:email)
        %span.val
          %span.text-nowrap= mail_to admin.email
      %li
        %span.key
          = t(:name)
        %span.val
          %span.text-nowrap= admin.name
      %li
        %span.key
          = t(:address)
        %span.val
          %span.text-nowrap= admin.full_address
      %li
        %span.key
          = t(:phone)
        %span.val
          %span.text-nowrap= number_to_phone(admin.phone)
      %li
        %span.key
          = t(:permissions)
        %span.val
          %span.text-nowrap
            - if admin.active
              .badge.badge-info= t(:active)
            - if admin.is_admin
              .badge.badge-info= t(:admin)
            - if admin.is_driver
              .badge.badge-info= t(:driver)
      %li
        %span.key
          = t(:employment_dates)
        %span.val
          %span.text-nowrap
            = admin.start_date
            till 
            - if admin.end_date.to_s.empty?
              Present
            - else
              = admin.end_date